include = ["**/Cargo.toml"]

[formatting]
align_entries = false

[[rule]]
keys = [
    "workspace.dependencies",
    "dependencies",
    "dev-dependencies",
    "patch.crates-io",
]

[rule.formatting]
reorder_keys = true
