exporter_endpoint = "http://quickwit:7281"
service_name = "public-worker-docker"

[server]
port = 8001
url = "0.0.0.0"

[log]
level = "info"

[pg]
max_size = 10
url = "postgres://postgres:changeme@postgres:5432/postgres"

[worker]
schema = "worker_schema"
concurrent = 4
