exporter_endpoint = "http://quickwit:7281"
service_name = "irelia"

[server]
port = 8888
url = "0.0.0.0"

[log]
level = "info"

[pg]
max_size = 10
url = "postgres://postgres:changeme@postgres:5432/postgres"
