exporter_endpoint = "http://0.0.0.0:7281"
service_name = "irelia-rest-api"

[pg]
max_size = 10
url = "postgres://postgres:changeme@0.0.0.0:5432/postgres"

[server]
port = 8000
url = "0.0.0.0"

[worker]
schema = "worker_schema"
