exporter_endpoint = "http://localhost:7281"
service_name = "irelia-worker"

[pg]
max_size = 10
url = "postgres://postgres:changeme@localhost:5432/postgres"

[server]
port = 8001
url = "0.0.0.0"

[worker]
schema = "worker_schema"
concurrent = 4

[verifier]
aptos_node_url =  "https://fullnode.testnet.aptoslabs.com"
aptos_private_key = "0x3d31ef06ed8003c3a85125b6e6287967a7b80a3e4367ccf2649e7acd574e4261"
aptos_chain_id = "testnet"
aptos_verifier_contract_address = "852578629621677c02f4b9679622f25cac00b4fe17d1fd8b197ba52a2627ee3b"