[package]
name = "adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.0"
serde = "1.0.210"
ethers = "2.0.14"
num-bigint = "0.4.6"
num-traits = "0.2.19"
thiserror = "1.0.64"
serde_json = "1.0.128"

